### ISSUE TITLE
Integrate with tracing

### ISSUE THREAD

**Issue by michaeldmitry** [canonical/parca-agent-operator#49]
### Enhancement Proposal

`parca-agent` has a workload tracing support
https://github.com/parca-dev/parca-agent/blob/68dcb27ca4292ca7e7ff38a80ec22d1b0fa3fecb/README.md?plain=1#L152

**Comment by PietroPasotti** [comment]
right now we have charm tracing on cos-agent's tracing endpoints

in kubernetes charms, we have decided to offer two endpoints: one for charm tracing and one for workload tracing.
in machine world, however, there's no such thing yet.
In a coherent world, we would:
  - extend cos-agent to also forward two separate tracing endpoints?
  - update grafana-agent to add a charm-tracing endpoint.

This way, charms that interface to cos-agent would be able to choose which endpoint to forward the charm vs workload traces to.

Problem is: grafana agent doesn't support forwarding two parallel streams; we'd be forced to run two grafana agents.
So: are we fine with having all traces (charm & workload) from machine charms go to the same stack, while we offer split stacks to k8s charms?

**Comment by mmkay** [comment]
> grafana agent doesn't support forwarding two parallel streams

This might be my wrong assumption, `configs` [here is a list](https://grafana.com/docs/agent/latest/static/configuration/create-config-file/#full-config-example) - so we might be able to keep separate streams per protocol. Tricky part here would be if we needed to reuse the same protocol twice - two separate ports then?

It'd look something like:

```
traces:
  configs:
  - name: charm_traces
    receivers:
      jaeger:
        protocols:
          grpc: # listens on the default jaeger grpc port: 14250
    remote_write:
      - endpoint: cluster-A:55680
    batch:
      timeout: 5s
      send_batch_size: 100
  - name: workload_traces
    receivers:
      jaeger:
        protocols:
          grpc: # listens on the default jaeger grpc port: 14250
              endpoint: 0.0.0.0:14251
    remote_write:
      - endpoint: cluster-B:55680
    batch:
      timeout: 5s
      send_batch_size: 100
```
